# Changes here will be overwritten by Copier
_commit: v7.1.0
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-python
project_description: Write ad-hoc transformations and workflow tasks with Python.
project_slug: python
project_type: plugin
pypi: true

